TESTING: false
folder_dependencies:
  embedding_dataset_folder: data/embedding_datasets/embeddings_V4
  VGG_model_folder: ''
folder_outputs: results/variants/_vgg_logits_softmax
wandb: false
experiment_prefix: BERT_
experiment_description: null
experiment_type: vgg_logits
embedding_norm: softmax
train_mode: full sequence
train_mode2: null
train_mode2_start: 4
vision_fine_tuning: false
vision_fine_tuning_start: 0
alphabet: abcdefghi jklmnopqrstuvwxyz
sentence_length: 32
attention_heads: 8
embedding_dim: 512
workers: 5
vgg_logits:
  loader_key: vgg_logits
  embedding_layer: true
vgg_embeddings:
  loader_key: data
  embedding_layer: false
language_only:
  loader_key: null
  train_mode: input occlusion
epochs: 20
max_updates: null
starting_epoch: null
batch_size: 192
save_freq_epoch: 1
epoch_length: 100000
lr: 0.0001
patience: 30
decay_factor: 0.5
steps_per_lr_update: 10
device: gpu
corpus: books
