# LR schedule
learning_rate: 1e-4          # LR
scheduler_step: null         # Every X steps, multiply LR by gamma
scheduler_gamma: .97         # LR decay rate

#
test_size: null   # number of items in test dataset loader - smaller for faster prototyping
train_size: null
batch_size: 28

# Main save folder
save_folder: ./data/embedding_datasets/V  # This will be incremented each experiment

#save_embedding_dataset_folder:
#save_VGG_model_folder:


gt_opts:
  - null
  - null
  - null
