TESTING: false
folder_dependencies:
  embedding_dataset_folder: data/embedding_datasets/embeddings_V5
  VGG_model_path: data/embedding_datasets/embeddings_V5/vgg.pt
  lm_model_path: lm/results/BASE/BERT_vgg_embeddings.pt
folder_outputs: results/variants/02_REDO/_vgg_logits_softmax_multicharacter MEAN_EMBEDDING_20
  RANDOM_CHAR_20 USE_CORRECT_CHAR_20
wandb: false
reset_optimizer: true
experiment_prefix: BERT_
experiment_description: null
experiment_type: vgg_logits
embedding_norm: softmax
train_mode: full sequence
train_mode2: multicharacter MEAN_EMBEDDING_20 RANDOM_CHAR_20 USE_CORRECT_CHAR_20
train_mode2_start: 0
train_mode2_probability: 0.6
vision_fine_tuning: false
vision_fine_tuning_start: 0
alphabet: abcdefghi jklmnopqrstuvwxyz
sentence_length: 32
attention_heads: 8
embedding_dim: 512
workers: 5
vgg_logits:
  loader_key: vgg_logits
  embedding_layer: true
vgg_embeddings:
  loader_key: embedding
  embedding_layer: false
language_only:
  loader_key: null
  train_mode: input occlusion
epochs: 40
max_updates: null
starting_epoch: null
batch_size: 384
save_freq_epoch: 1
epoch_length: 100000
lr: 0.0001
patience: 30
decay_factor: 0.5
steps_per_lr_update: 10
device: gpu
corpus: books
lm_model_path: lm/results/BASE/BERT_vgg_logits.pt
